
file:
  repo:
    path: /Users/cbidici/Desktop/calis
    thumbnail:
      directory: thumbnails
      width: 200
    optimized:
      directory: optimized
      width: 854

---
spring:
  profiles:
    active: prod
