
file:
  repo:
    path: e:\\\foto
    thumbnail:
      directory: thumbnails
      width: 200
    optimized:
      directory: optimized
      width: 512, 1024, 2048

---
spring:
  profiles:
    active: prod
