
file:
  repo:
    path: e:\\\foto
    thumbnail:
      directory: thumbnails
      width: 200
    optimized:
      directory: optimized
      width: 426, 854, 1920

---
spring:
  profiles:
    active: prod
